#!/usr/bin/env zsh

# Set main dotfiles directory
DOTFILES=$PWD/../

# Include dotfiles in .zshrc
if ! fgrep -q 'source ~/.zsh/main.zsh' ~/.zshrc; then
  echo "source ~/.zsh/main.zsh" >> ~/.zshrc
fi;

# Include functions
source $DOTFILES/functions.zsh

# Include exports
source $DOTFILES/exports.zsh

if [[ $OS == "macos" ]]; then
    source $DOTFILES/tools/apps
fi

# Ask for the administrator password upfront
sudo -v

# Install git submodules
cd $DOTFILES
git submodule init
git submodule update

# Install FuzzyFinder
$DOTFILES/plugins/fzf/install --key-bindings --completion --no-update-rc

# If prompt executable set as haskell build prompt aplication
if [[ $GIT_PROMPT_EXECUTABLE = 'haskell' ]]; then
    cd $DOTFILES/oh-my-zsh/custom/plugins/zsh-git-prompt/src
    stack setup && stack build && stack install
fi;

# Copy config files to HOME directory
cp $DOTFILES/configs/vimrc $HOME/.vimrc
cp -R $DOTFILES/configs/vim $HOME/.vim